resolver: lts-19.9

packages:
- haskus-utils-compat/
- haskus-utils/
- haskus-utils-types/
- haskus-utils-data/
- haskus-utils-variant/
- haskus-binary/
- haskus-web/
- haskus-text/
- haskus-locale/
- haskus-calculus/
- haskus-graphics/
- haskus-ui/
- haskus-time/
- haskus-maths/
- haskus-maps/

ghc-options:
   "$locals": -fhide-source-paths -freverse-errors

build:
   interleaved-output: true

extra-deps: 
- doctest-parallel-0.3.1@sha256:f1ec7b7044d156dacf3bc5464c9c692d12f490ec8bb933c6a9007d98c42004d5,5862
