name:                haskus-maths
version:             0.1
github:              "haskus/packages"
license:             BSD3
author:              "Sylvain HENRY"
maintainer:          "sylvain@haskus.fr"
copyright:           "Sylvain HENRY 2019"

synopsis:            Maths related functions
category:            Maths

description:         Please see the README on Github at <https://github.com/haskus/packages/#readme>

dependencies:
- base >= 4.8 && < 5
- haskus-utils
- haskus-utils-data
- haskus-utils-variant
- linear
- containers

ghc-options: -Wall -O

library:
   source-dirs: src/lib
   exposed-modules:
      - Haskus.Maths.Geometry.Polygon
      - Haskus.Maths.Geometry.Line
      - Haskus.Maths.Geometry.Segment
      - Haskus.Maths.Geometry.Point
      - Haskus.Maths.Logic.Propositional

tests:
   main-tests:
      main: Main.hs
      source-dirs: src/tests
      dependencies:
         - doctest
