name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: [master]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.3"

    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: "latest"

    - run: cabal build all
    - run: cabal test all -j1

  stack:
    name: stack
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      name: Setup Haskell Stack
      with:
        ghc-version: 'ghc-9.4.7'
        stack-version: 'latest'
        enable-stack: true
        stack-no-global: true
        stack-setup-ghc: true

    - name: Build
      run: |
        stack build --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test -j1
        # we need -j1 because of https://github.com/commercialhaskell/stack/issues/5159
